[project]
name = "command-over-zmq"
version = "0.1.0"
description = "A clinet and server to run OS commands over socket using ZeroMQ"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiofile>=3.9.0",
    "pydantic>=2.11.4",
    "pyzmq>=26.4.0",
    "rich>=14.0.0",
]
